trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: titanic-api
  REGISTRY: titanicmlacr712b018f.azurecr.io
  TAG: latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
    pytest tests/
  displayName: 'Run unit tests'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: $(REGISTRY)/$(IMAGE_NAME)
    command: build
    Dockerfile: docker/Dockerfile
    tags: |
      $(TAG)

- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: 'titanic-ml-acr-docker-connection'

- task: Docker@2
  displayName: 'Push Docker image'
  inputs:
    repository: $(REGISTRY)/$(IMAGE_NAME)
    command: push
    tags: |
      $(TAG)
